// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: bilibili/app/dynamic/common/dynamic.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WHRatio int32

const (
	WHRatio_W_H_RATIO_1_1    WHRatio = 0
	WHRatio_W_H_RATIO_16_9   WHRatio = 1
	WHRatio_W_H_RATIO_3_4    WHRatio = 2
	WHRatio_W_H_RATIO_CUSTOM WHRatio = 3
)

// Enum value maps for WHRatio.
var (
	WHRatio_name = map[int32]string{
		0: "W_H_RATIO_1_1",
		1: "W_H_RATIO_16_9",
		2: "W_H_RATIO_3_4",
		3: "W_H_RATIO_CUSTOM",
	}
	WHRatio_value = map[string]int32{
		"W_H_RATIO_1_1":    0,
		"W_H_RATIO_16_9":   1,
		"W_H_RATIO_3_4":    2,
		"W_H_RATIO_CUSTOM": 3,
	}
)

func (x WHRatio) Enum() *WHRatio {
	p := new(WHRatio)
	*p = x
	return p
}

func (x WHRatio) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WHRatio) Descriptor() protoreflect.EnumDescriptor {
	return file_bilibili_app_dynamic_common_dynamic_proto_enumTypes[0].Descriptor()
}

func (WHRatio) Type() protoreflect.EnumType {
	return &file_bilibili_app_dynamic_common_dynamic_proto_enumTypes[0]
}

func (x WHRatio) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WHRatio.Descriptor instead.
func (WHRatio) EnumDescriptor() ([]byte, []int) {
	return file_bilibili_app_dynamic_common_dynamic_proto_rawDescGZIP(), []int{0}
}

type ItemWHRatio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ratio int32 `protobuf:"varint,1,opt,name=ratio,proto3" json:"ratio,omitempty"`
	Width int32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height int32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *ItemWHRatio) Reset() {
	*x = ItemWHRatio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_dynamic_common_dynamic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemWHRatio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemWHRatio) ProtoMessage() {}

func (x *ItemWHRatio) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_dynamic_common_dynamic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemWHRatio.ProtoReflect.Descriptor instead.
func (*ItemWHRatio) Descriptor() ([]byte, []int) {
	return file_bilibili_app_dynamic_common_dynamic_proto_rawDescGZIP(), []int{0}
}

func (x *ItemWHRatio) GetRatio() int32 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *ItemWHRatio) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ItemWHRatio) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_bilibili_app_dynamic_common_dynamic_proto protoreflect.FileDescriptor

var file_bilibili_app_dynamic_common_dynamic_proto_rawDesc = []byte{
	0x0a, 0x29, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x64,
	0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x64, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x62, 0x69, 0x6c,
	0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69,
	0x63, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x51, 0x0a, 0x0b, 0x49, 0x74, 0x65, 0x6d,
	0x57, 0x48, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x2a, 0x59, 0x0a, 0x07, 0x57,
	0x48, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x11, 0x0a, 0x0d, 0x57, 0x5f, 0x48, 0x5f, 0x52, 0x41,
	0x54, 0x49, 0x4f, 0x5f, 0x31, 0x5f, 0x31, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x57, 0x5f, 0x48,
	0x5f, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x5f, 0x31, 0x36, 0x5f, 0x39, 0x10, 0x01, 0x12, 0x11, 0x0a,
	0x0d, 0x57, 0x5f, 0x48, 0x5f, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x5f, 0x33, 0x5f, 0x34, 0x10, 0x02,
	0x12, 0x14, 0x0a, 0x10, 0x57, 0x5f, 0x48, 0x5f, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x5f, 0x43, 0x55,
	0x53, 0x54, 0x4f, 0x4d, 0x10, 0x03, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x58, 0x69, 0x61, 0x6f, 0x4d, 0x69, 0x6b, 0x75, 0x30, 0x31, 0x2f,
	0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x61, 0x70,
	0x69, 0x2d, 0x67, 0x6f, 0x2f, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x61, 0x70,
	0x70, 0x2f, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bilibili_app_dynamic_common_dynamic_proto_rawDescOnce sync.Once
	file_bilibili_app_dynamic_common_dynamic_proto_rawDescData = file_bilibili_app_dynamic_common_dynamic_proto_rawDesc
)

func file_bilibili_app_dynamic_common_dynamic_proto_rawDescGZIP() []byte {
	file_bilibili_app_dynamic_common_dynamic_proto_rawDescOnce.Do(func() {
		file_bilibili_app_dynamic_common_dynamic_proto_rawDescData = protoimpl.X.CompressGZIP(file_bilibili_app_dynamic_common_dynamic_proto_rawDescData)
	})
	return file_bilibili_app_dynamic_common_dynamic_proto_rawDescData
}

var file_bilibili_app_dynamic_common_dynamic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bilibili_app_dynamic_common_dynamic_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bilibili_app_dynamic_common_dynamic_proto_goTypes = []interface{}{
	(WHRatio)(0),        // 0: bilibili.app.dynamic.common.WHRatio
	(*ItemWHRatio)(nil), // 1: bilibili.app.dynamic.common.ItemWHRatio
}
var file_bilibili_app_dynamic_common_dynamic_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bilibili_app_dynamic_common_dynamic_proto_init() }
func file_bilibili_app_dynamic_common_dynamic_proto_init() {
	if File_bilibili_app_dynamic_common_dynamic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bilibili_app_dynamic_common_dynamic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemWHRatio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bilibili_app_dynamic_common_dynamic_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bilibili_app_dynamic_common_dynamic_proto_goTypes,
		DependencyIndexes: file_bilibili_app_dynamic_common_dynamic_proto_depIdxs,
		EnumInfos:         file_bilibili_app_dynamic_common_dynamic_proto_enumTypes,
		MessageInfos:      file_bilibili_app_dynamic_common_dynamic_proto_msgTypes,
	}.Build()
	File_bilibili_app_dynamic_common_dynamic_proto = out.File
	file_bilibili_app_dynamic_common_dynamic_proto_rawDesc = nil
	file_bilibili_app_dynamic_common_dynamic_proto_goTypes = nil
	file_bilibili_app_dynamic_common_dynamic_proto_depIdxs = nil
}
