// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: bilibili/broadcast/message/ogv/live.proto

package ogv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 开播事件
type LiveStartEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LiveStartEvent) Reset() {
	*x = LiveStartEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_broadcast_message_ogv_live_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveStartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveStartEvent) ProtoMessage() {}

func (x *LiveStartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_broadcast_message_ogv_live_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveStartEvent.ProtoReflect.Descriptor instead.
func (*LiveStartEvent) Descriptor() ([]byte, []int) {
	return file_bilibili_broadcast_message_ogv_live_proto_rawDescGZIP(), []int{0}
}

// 直播中止事件
type LiveEndEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LiveEndEvent) Reset() {
	*x = LiveEndEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_broadcast_message_ogv_live_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveEndEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveEndEvent) ProtoMessage() {}

func (x *LiveEndEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_broadcast_message_ogv_live_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveEndEvent.ProtoReflect.Descriptor instead.
func (*LiveEndEvent) Descriptor() ([]byte, []int) {
	return file_bilibili_broadcast_message_ogv_live_proto_rawDescGZIP(), []int{1}
}

// 在线人数事件
type LiveOnlineEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 在线人数
	Online int64 `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
}

func (x *LiveOnlineEvent) Reset() {
	*x = LiveOnlineEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_broadcast_message_ogv_live_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveOnlineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveOnlineEvent) ProtoMessage() {}

func (x *LiveOnlineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_broadcast_message_ogv_live_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveOnlineEvent.ProtoReflect.Descriptor instead.
func (*LiveOnlineEvent) Descriptor() ([]byte, []int) {
	return file_bilibili_broadcast_message_ogv_live_proto_rawDescGZIP(), []int{2}
}

func (x *LiveOnlineEvent) GetOnline() int64 {
	if x != nil {
		return x.Online
	}
	return 0
}

// 变更通知
type LiveUpdateEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 直播后状态
	// 1:下线 2:转点播
	AfterPremiereType int32 `protobuf:"varint,1,opt,name=after_premiere_type,json=afterPremiereType,proto3" json:"after_premiere_type,omitempty"`
	// 直播开始绝对时间 单位ms
	StartTime int64 `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// id
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// 服务端播放进度，未打散，负数表示距离开播时间，正数表示已开播时间，单位：毫秒
	// 用户实际播放进度：progress - delay_time
	Progress int64 `protobuf:"varint,4,opt,name=progress,proto3" json:"progress,omitempty"`
}

func (x *LiveUpdateEvent) Reset() {
	*x = LiveUpdateEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_broadcast_message_ogv_live_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveUpdateEvent) ProtoMessage() {}

func (x *LiveUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_broadcast_message_ogv_live_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveUpdateEvent.ProtoReflect.Descriptor instead.
func (*LiveUpdateEvent) Descriptor() ([]byte, []int) {
	return file_bilibili_broadcast_message_ogv_live_proto_rawDescGZIP(), []int{3}
}

func (x *LiveUpdateEvent) GetAfterPremiereType() int32 {
	if x != nil {
		return x.AfterPremiereType
	}
	return 0
}

func (x *LiveUpdateEvent) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *LiveUpdateEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LiveUpdateEvent) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

// 直播间事件
type CMDBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 命令类型
	//
	// Types that are assignable to Event:
	//
	//	*CMDBody_Start
	//	*CMDBody_Emergency
	//	*CMDBody_Online
	//	*CMDBody_Update
	Event isCMDBody_Event `protobuf_oneof:"event"`
}

func (x *CMDBody) Reset() {
	*x = CMDBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_broadcast_message_ogv_live_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CMDBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMDBody) ProtoMessage() {}

func (x *CMDBody) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_broadcast_message_ogv_live_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMDBody.ProtoReflect.Descriptor instead.
func (*CMDBody) Descriptor() ([]byte, []int) {
	return file_bilibili_broadcast_message_ogv_live_proto_rawDescGZIP(), []int{4}
}

func (m *CMDBody) GetEvent() isCMDBody_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *CMDBody) GetStart() *LiveStartEvent {
	if x, ok := x.GetEvent().(*CMDBody_Start); ok {
		return x.Start
	}
	return nil
}

func (x *CMDBody) GetEmergency() *LiveEndEvent {
	if x, ok := x.GetEvent().(*CMDBody_Emergency); ok {
		return x.Emergency
	}
	return nil
}

func (x *CMDBody) GetOnline() *LiveOnlineEvent {
	if x, ok := x.GetEvent().(*CMDBody_Online); ok {
		return x.Online
	}
	return nil
}

func (x *CMDBody) GetUpdate() *LiveUpdateEvent {
	if x, ok := x.GetEvent().(*CMDBody_Update); ok {
		return x.Update
	}
	return nil
}

type isCMDBody_Event interface {
	isCMDBody_Event()
}

type CMDBody_Start struct {
	// 开播事件
	Start *LiveStartEvent `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type CMDBody_Emergency struct {
	// 直播中止事件
	Emergency *LiveEndEvent `protobuf:"bytes,2,opt,name=emergency,proto3,oneof"`
}

type CMDBody_Online struct {
	// 在线人数事件
	Online *LiveOnlineEvent `protobuf:"bytes,3,opt,name=online,proto3,oneof"`
}

type CMDBody_Update struct {
	// 变更通知
	Update *LiveUpdateEvent `protobuf:"bytes,4,opt,name=update,proto3,oneof"`
}

func (*CMDBody_Start) isCMDBody_Event() {}

func (*CMDBody_Emergency) isCMDBody_Event() {}

func (*CMDBody_Online) isCMDBody_Event() {}

func (*CMDBody_Update) isCMDBody_Event() {}

var File_bilibili_broadcast_message_ogv_live_proto protoreflect.FileDescriptor

var file_bilibili_broadcast_message_ogv_live_proto_rawDesc = []byte{
	0x0a, 0x29, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x62, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x6f, 0x67, 0x76,
	0x2f, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x62, 0x69, 0x6c,
	0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x6f, 0x67, 0x76, 0x22, 0x10, 0x0a, 0x0e, 0x4c,
	0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x0e, 0x0a,
	0x0c, 0x4c, 0x69, 0x76, 0x65, 0x45, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x29, 0x0a,
	0x0f, 0x4c, 0x69, 0x76, 0x65, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x8c, 0x01, 0x0a, 0x0f, 0x4c, 0x69, 0x76,
	0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x13,
	0x61, 0x66, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x65, 0x6d, 0x69, 0x65, 0x72, 0x65, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x61, 0x66, 0x74, 0x65, 0x72,
	0x50, 0x72, 0x65, 0x6d, 0x69, 0x65, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70,
	0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x22, 0xbe, 0x02, 0x0a, 0x07, 0x43, 0x4d, 0x44, 0x42,
	0x6f, 0x64, 0x79, 0x12, 0x46, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x62, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x6f, 0x67, 0x76, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x4c, 0x0a, 0x09, 0x65,
	0x6d, 0x65, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c,
	0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63,
	0x61, 0x73, 0x74, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x6f, 0x67, 0x76, 0x2e,
	0x4c, 0x69, 0x76, 0x65, 0x45, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x09,
	0x65, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x49, 0x0a, 0x06, 0x6f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x62, 0x69, 0x6c, 0x69,
	0x62, 0x69, 0x6c, 0x69, 0x2e, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x6f, 0x67, 0x76, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x12, 0x49, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e,
	0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x6f, 0x67, 0x76, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42,
	0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x4b, 0x5a, 0x49, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x58, 0x69, 0x61, 0x6f, 0x4d, 0x69, 0x6b, 0x75, 0x30,
	0x31, 0x2f, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d,
	0x61, 0x70, 0x69, 0x2d, 0x67, 0x6f, 0x2f, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f,
	0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2f, 0x6f, 0x67, 0x76, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bilibili_broadcast_message_ogv_live_proto_rawDescOnce sync.Once
	file_bilibili_broadcast_message_ogv_live_proto_rawDescData = file_bilibili_broadcast_message_ogv_live_proto_rawDesc
)

func file_bilibili_broadcast_message_ogv_live_proto_rawDescGZIP() []byte {
	file_bilibili_broadcast_message_ogv_live_proto_rawDescOnce.Do(func() {
		file_bilibili_broadcast_message_ogv_live_proto_rawDescData = protoimpl.X.CompressGZIP(file_bilibili_broadcast_message_ogv_live_proto_rawDescData)
	})
	return file_bilibili_broadcast_message_ogv_live_proto_rawDescData
}

var file_bilibili_broadcast_message_ogv_live_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_bilibili_broadcast_message_ogv_live_proto_goTypes = []interface{}{
	(*LiveStartEvent)(nil),  // 0: bilibili.broadcast.message.ogv.LiveStartEvent
	(*LiveEndEvent)(nil),    // 1: bilibili.broadcast.message.ogv.LiveEndEvent
	(*LiveOnlineEvent)(nil), // 2: bilibili.broadcast.message.ogv.LiveOnlineEvent
	(*LiveUpdateEvent)(nil), // 3: bilibili.broadcast.message.ogv.LiveUpdateEvent
	(*CMDBody)(nil),         // 4: bilibili.broadcast.message.ogv.CMDBody
}
var file_bilibili_broadcast_message_ogv_live_proto_depIdxs = []int32{
	0, // 0: bilibili.broadcast.message.ogv.CMDBody.start:type_name -> bilibili.broadcast.message.ogv.LiveStartEvent
	1, // 1: bilibili.broadcast.message.ogv.CMDBody.emergency:type_name -> bilibili.broadcast.message.ogv.LiveEndEvent
	2, // 2: bilibili.broadcast.message.ogv.CMDBody.online:type_name -> bilibili.broadcast.message.ogv.LiveOnlineEvent
	3, // 3: bilibili.broadcast.message.ogv.CMDBody.update:type_name -> bilibili.broadcast.message.ogv.LiveUpdateEvent
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bilibili_broadcast_message_ogv_live_proto_init() }
func file_bilibili_broadcast_message_ogv_live_proto_init() {
	if File_bilibili_broadcast_message_ogv_live_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bilibili_broadcast_message_ogv_live_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveStartEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_broadcast_message_ogv_live_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveEndEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_broadcast_message_ogv_live_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveOnlineEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_broadcast_message_ogv_live_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveUpdateEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_broadcast_message_ogv_live_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CMDBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bilibili_broadcast_message_ogv_live_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*CMDBody_Start)(nil),
		(*CMDBody_Emergency)(nil),
		(*CMDBody_Online)(nil),
		(*CMDBody_Update)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bilibili_broadcast_message_ogv_live_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bilibili_broadcast_message_ogv_live_proto_goTypes,
		DependencyIndexes: file_bilibili_broadcast_message_ogv_live_proto_depIdxs,
		MessageInfos:      file_bilibili_broadcast_message_ogv_live_proto_msgTypes,
	}.Build()
	File_bilibili_broadcast_message_ogv_live_proto = out.File
	file_bilibili_broadcast_message_ogv_live_proto_rawDesc = nil
	file_bilibili_broadcast_message_ogv_live_proto_goTypes = nil
	file_bilibili_broadcast_message_ogv_live_proto_depIdxs = nil
}
