// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: bilibili/app/distribution/setting/dynamic.proto

package setting

import (
	v1 "github.com/XiaoMiku01/bilibili-grpc-api-go/bilibili/app/distribution/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DynamicAutoPlay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *v1.Int64Value `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DynamicAutoPlay) Reset() {
	*x = DynamicAutoPlay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_distribution_setting_dynamic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynamicAutoPlay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicAutoPlay) ProtoMessage() {}

func (x *DynamicAutoPlay) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_distribution_setting_dynamic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicAutoPlay.ProtoReflect.Descriptor instead.
func (*DynamicAutoPlay) Descriptor() ([]byte, []int) {
	return file_bilibili_app_distribution_setting_dynamic_proto_rawDescGZIP(), []int{0}
}

func (x *DynamicAutoPlay) GetValue() *v1.Int64Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type DynamicDeviceConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AutoPlay *DynamicAutoPlay `protobuf:"bytes,1,opt,name=auto_play,json=autoPlay,proto3" json:"auto_play,omitempty"`
}

func (x *DynamicDeviceConfig) Reset() {
	*x = DynamicDeviceConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_distribution_setting_dynamic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynamicDeviceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicDeviceConfig) ProtoMessage() {}

func (x *DynamicDeviceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_distribution_setting_dynamic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicDeviceConfig.ProtoReflect.Descriptor instead.
func (*DynamicDeviceConfig) Descriptor() ([]byte, []int) {
	return file_bilibili_app_distribution_setting_dynamic_proto_rawDescGZIP(), []int{1}
}

func (x *DynamicDeviceConfig) GetAutoPlay() *DynamicAutoPlay {
	if x != nil {
		return x.AutoPlay
	}
	return nil
}

var File_bilibili_app_distribution_setting_dynamic_proto protoreflect.FileDescriptor

var file_bilibili_app_distribution_setting_dynamic_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x2f, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x29, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x1a, 0x2f, 0x62, 0x69,
	0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x51, 0x0a,
	0x0f, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x41, 0x75, 0x74, 0x6f, 0x50, 0x6c, 0x61, 0x79,
	0x12, 0x3e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x28, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x49,
	0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x6e, 0x0a, 0x13, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x57, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x6f, 0x5f,
	0x70, 0x6c, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x62, 0x69, 0x6c,
	0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x64,
	0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x41, 0x75,
	0x74, 0x6f, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x08, 0x61, 0x75, 0x74, 0x6f, 0x50, 0x6c, 0x61, 0x79,
	0x42, 0x4e, 0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x58,
	0x69, 0x61, 0x6f, 0x4d, 0x69, 0x6b, 0x75, 0x30, 0x31, 0x2f, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69,
	0x6c, 0x69, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x6f, 0x2f, 0x62,
	0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x64, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bilibili_app_distribution_setting_dynamic_proto_rawDescOnce sync.Once
	file_bilibili_app_distribution_setting_dynamic_proto_rawDescData = file_bilibili_app_distribution_setting_dynamic_proto_rawDesc
)

func file_bilibili_app_distribution_setting_dynamic_proto_rawDescGZIP() []byte {
	file_bilibili_app_distribution_setting_dynamic_proto_rawDescOnce.Do(func() {
		file_bilibili_app_distribution_setting_dynamic_proto_rawDescData = protoimpl.X.CompressGZIP(file_bilibili_app_distribution_setting_dynamic_proto_rawDescData)
	})
	return file_bilibili_app_distribution_setting_dynamic_proto_rawDescData
}

var file_bilibili_app_distribution_setting_dynamic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bilibili_app_distribution_setting_dynamic_proto_goTypes = []interface{}{
	(*DynamicAutoPlay)(nil),     // 0: bilibili.app.distribution.setting.dynamic.DynamicAutoPlay
	(*DynamicDeviceConfig)(nil), // 1: bilibili.app.distribution.setting.dynamic.DynamicDeviceConfig
	(*v1.Int64Value)(nil),       // 2: bilibili.app.distribution.v1.Int64Value
}
var file_bilibili_app_distribution_setting_dynamic_proto_depIdxs = []int32{
	2, // 0: bilibili.app.distribution.setting.dynamic.DynamicAutoPlay.value:type_name -> bilibili.app.distribution.v1.Int64Value
	0, // 1: bilibili.app.distribution.setting.dynamic.DynamicDeviceConfig.auto_play:type_name -> bilibili.app.distribution.setting.dynamic.DynamicAutoPlay
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bilibili_app_distribution_setting_dynamic_proto_init() }
func file_bilibili_app_distribution_setting_dynamic_proto_init() {
	if File_bilibili_app_distribution_setting_dynamic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bilibili_app_distribution_setting_dynamic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DynamicAutoPlay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_distribution_setting_dynamic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DynamicDeviceConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bilibili_app_distribution_setting_dynamic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bilibili_app_distribution_setting_dynamic_proto_goTypes,
		DependencyIndexes: file_bilibili_app_distribution_setting_dynamic_proto_depIdxs,
		MessageInfos:      file_bilibili_app_distribution_setting_dynamic_proto_msgTypes,
	}.Build()
	File_bilibili_app_distribution_setting_dynamic_proto = out.File
	file_bilibili_app_distribution_setting_dynamic_proto_rawDesc = nil
	file_bilibili_app_distribution_setting_dynamic_proto_goTypes = nil
	file_bilibili_app_distribution_setting_dynamic_proto_depIdxs = nil
}
