// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: bilibili/web/space/v1/space.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopPhotoType int32

const (
	TopPhotoType_UNKNOWN TopPhotoType = 0 //
	TopPhotoType_PIC     TopPhotoType = 1 //
	TopPhotoType_ARCHIVE TopPhotoType = 2 //
)

// Enum value maps for TopPhotoType.
var (
	TopPhotoType_name = map[int32]string{
		0: "UNKNOWN",
		1: "PIC",
		2: "ARCHIVE",
	}
	TopPhotoType_value = map[string]int32{
		"UNKNOWN": 0,
		"PIC":     1,
		"ARCHIVE": 2,
	}
)

func (x TopPhotoType) Enum() *TopPhotoType {
	p := new(TopPhotoType)
	*p = x
	return p
}

func (x TopPhotoType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TopPhotoType) Descriptor() protoreflect.EnumDescriptor {
	return file_bilibili_web_space_v1_space_proto_enumTypes[0].Descriptor()
}

func (TopPhotoType) Type() protoreflect.EnumType {
	return &file_bilibili_web_space_v1_space_proto_enumTypes[0]
}

func (x TopPhotoType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TopPhotoType.Descriptor instead.
func (TopPhotoType) EnumDescriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{0}
}

type NoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoReply) Reset() {
	*x = NoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoReply) ProtoMessage() {}

func (x *NoReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoReply.ProtoReflect.Descriptor instead.
func (*NoReply) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{0}
}

type OfficialReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid        int64  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Icon       string `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Scheme     string `protobuf:"bytes,5,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Rcmd       string `protobuf:"bytes,6,opt,name=rcmd,proto3" json:"rcmd,omitempty"`
	IosUrl     string `protobuf:"bytes,7,opt,name=ios_url,json=iosUrl,proto3" json:"ios_url,omitempty"`
	AndroidUrl string `protobuf:"bytes,8,opt,name=android_url,json=androidUrl,proto3" json:"android_url,omitempty"`
	Button     string `protobuf:"bytes,9,opt,name=button,proto3" json:"button,omitempty"`
	Deleted    string `protobuf:"bytes,10,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Mtime      int64  `protobuf:"varint,11,opt,name=mtime,proto3" json:"mtime,omitempty"`
}

func (x *OfficialReply) Reset() {
	*x = OfficialReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfficialReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfficialReply) ProtoMessage() {}

func (x *OfficialReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfficialReply.ProtoReflect.Descriptor instead.
func (*OfficialReply) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{1}
}

func (x *OfficialReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OfficialReply) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *OfficialReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OfficialReply) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *OfficialReply) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *OfficialReply) GetRcmd() string {
	if x != nil {
		return x.Rcmd
	}
	return ""
}

func (x *OfficialReply) GetIosUrl() string {
	if x != nil {
		return x.IosUrl
	}
	return ""
}

func (x *OfficialReply) GetAndroidUrl() string {
	if x != nil {
		return x.AndroidUrl
	}
	return ""
}

func (x *OfficialReply) GetButton() string {
	if x != nil {
		return x.Button
	}
	return ""
}

func (x *OfficialReply) GetDeleted() string {
	if x != nil {
		return x.Deleted
	}
	return ""
}

func (x *OfficialReply) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

type OfficialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mid int64 `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
}

func (x *OfficialRequest) Reset() {
	*x = OfficialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfficialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfficialRequest) ProtoMessage() {}

func (x *OfficialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfficialRequest.ProtoReflect.Descriptor instead.
func (*OfficialRequest) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{2}
}

func (x *OfficialRequest) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

type PhotoMall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Img         string `protobuf:"bytes,3,opt,name=img,proto3" json:"img,omitempty"`
	NightImg    string `protobuf:"bytes,4,opt,name=night_img,json=nightImg,proto3" json:"night_img,omitempty"`
	IsActivated int64  `protobuf:"varint,5,opt,name=is_activated,json=isActivated,proto3" json:"is_activated,omitempty"`
}

func (x *PhotoMall) Reset() {
	*x = PhotoMall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhotoMall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoMall) ProtoMessage() {}

func (x *PhotoMall) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoMall.ProtoReflect.Descriptor instead.
func (*PhotoMall) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{3}
}

func (x *PhotoMall) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PhotoMall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PhotoMall) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

func (x *PhotoMall) GetNightImg() string {
	if x != nil {
		return x.NightImg
	}
	return ""
}

func (x *PhotoMall) GetIsActivated() int64 {
	if x != nil {
		return x.IsActivated
	}
	return 0
}

type PhotoMallListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*PhotoMall `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *PhotoMallListReply) Reset() {
	*x = PhotoMallListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhotoMallListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoMallListReply) ProtoMessage() {}

func (x *PhotoMallListReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoMallListReply.ProtoReflect.Descriptor instead.
func (*PhotoMallListReply) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{4}
}

func (x *PhotoMallListReply) GetList() []*PhotoMall {
	if x != nil {
		return x.List
	}
	return nil
}

type PhotoMallListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobiapp string `protobuf:"bytes,1,opt,name=mobiapp,proto3" json:"mobiapp,omitempty"`
	Mid     int64  `protobuf:"varint,2,opt,name=mid,proto3" json:"mid,omitempty"`
	Device  string `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
}

func (x *PhotoMallListReq) Reset() {
	*x = PhotoMallListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhotoMallListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoMallListReq) ProtoMessage() {}

func (x *PhotoMallListReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoMallListReq.ProtoReflect.Descriptor instead.
func (*PhotoMallListReq) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{5}
}

func (x *PhotoMallListReq) GetMobiapp() string {
	if x != nil {
		return x.Mobiapp
	}
	return ""
}

func (x *PhotoMallListReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *PhotoMallListReq) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type PrivacyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Privacy map[string]int64 `protobuf:"bytes,1,rep,name=privacy,proto3" json:"privacy,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *PrivacyReply) Reset() {
	*x = PrivacyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivacyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivacyReply) ProtoMessage() {}

func (x *PrivacyReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivacyReply.ProtoReflect.Descriptor instead.
func (*PrivacyReply) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{6}
}

func (x *PrivacyReply) GetPrivacy() map[string]int64 {
	if x != nil {
		return x.Privacy
	}
	return nil
}

type PrivacyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mid int64 `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
}

func (x *PrivacyRequest) Reset() {
	*x = PrivacyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivacyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivacyRequest) ProtoMessage() {}

func (x *PrivacyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivacyRequest.ProtoReflect.Descriptor instead.
func (*PrivacyRequest) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{7}
}

func (x *PrivacyRequest) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

type SetTopPhotoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobiapp string `protobuf:"bytes,1,opt,name=mobiapp,proto3" json:"mobiapp,omitempty"`
	ID      int64  `protobuf:"varint,2,opt,name=i_d,json=iD,proto3" json:"i_d,omitempty"`
	Mid     int64  `protobuf:"varint,3,opt,name=mid,proto3" json:"mid,omitempty"`
	Type    int32  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *SetTopPhotoReq) Reset() {
	*x = SetTopPhotoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTopPhotoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTopPhotoReq) ProtoMessage() {}

func (x *SetTopPhotoReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTopPhotoReq.ProtoReflect.Descriptor instead.
func (*SetTopPhotoReq) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{8}
}

func (x *SetTopPhotoReq) GetMobiapp() string {
	if x != nil {
		return x.Mobiapp
	}
	return ""
}

func (x *SetTopPhotoReq) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *SetTopPhotoReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *SetTopPhotoReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type SpaceSettingReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel           int64 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	FavVideo          int64 `protobuf:"varint,2,opt,name=fav_video,json=favVideo,proto3" json:"fav_video,omitempty"`
	CoinsVideo        int64 `protobuf:"varint,3,opt,name=coins_video,json=coinsVideo,proto3" json:"coins_video,omitempty"`
	LikesVideo        int64 `protobuf:"varint,4,opt,name=likes_video,json=likesVideo,proto3" json:"likes_video,omitempty"`
	Bangumi           int64 `protobuf:"varint,5,opt,name=bangumi,proto3" json:"bangumi,omitempty"`
	PlayedGame        int64 `protobuf:"varint,6,opt,name=played_game,json=playedGame,proto3" json:"played_game,omitempty"`
	Groups            int64 `protobuf:"varint,7,opt,name=groups,proto3" json:"groups,omitempty"`
	Comic             int64 `protobuf:"varint,8,opt,name=comic,proto3" json:"comic,omitempty"`
	BBq               int64 `protobuf:"varint,9,opt,name=b_bq,json=bBq,proto3" json:"b_bq,omitempty"`
	DressUp           int64 `protobuf:"varint,10,opt,name=dress_up,json=dressUp,proto3" json:"dress_up,omitempty"`
	DisableFollowing  int64 `protobuf:"varint,11,opt,name=disable_following,json=disableFollowing,proto3" json:"disable_following,omitempty"`
	LivePlayback      int64 `protobuf:"varint,12,opt,name=live_playback,json=livePlayback,proto3" json:"live_playback,omitempty"`
	CloseSpaceMedal   int64 `protobuf:"varint,13,opt,name=close_space_medal,json=closeSpaceMedal,proto3" json:"close_space_medal,omitempty"`
	OnlyShowWearing   int64 `protobuf:"varint,14,opt,name=only_show_wearing,json=onlyShowWearing,proto3" json:"only_show_wearing,omitempty"`
	DisableShowSchool int64 `protobuf:"varint,15,opt,name=disable_show_school,json=disableShowSchool,proto3" json:"disable_show_school,omitempty"`
	DisableShowNft    int64 `protobuf:"varint,16,opt,name=disable_show_nft,json=disableShowNft,proto3" json:"disable_show_nft,omitempty"`
}

func (x *SpaceSettingReply) Reset() {
	*x = SpaceSettingReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceSettingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceSettingReply) ProtoMessage() {}

func (x *SpaceSettingReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceSettingReply.ProtoReflect.Descriptor instead.
func (*SpaceSettingReply) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{9}
}

func (x *SpaceSettingReply) GetChannel() int64 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *SpaceSettingReply) GetFavVideo() int64 {
	if x != nil {
		return x.FavVideo
	}
	return 0
}

func (x *SpaceSettingReply) GetCoinsVideo() int64 {
	if x != nil {
		return x.CoinsVideo
	}
	return 0
}

func (x *SpaceSettingReply) GetLikesVideo() int64 {
	if x != nil {
		return x.LikesVideo
	}
	return 0
}

func (x *SpaceSettingReply) GetBangumi() int64 {
	if x != nil {
		return x.Bangumi
	}
	return 0
}

func (x *SpaceSettingReply) GetPlayedGame() int64 {
	if x != nil {
		return x.PlayedGame
	}
	return 0
}

func (x *SpaceSettingReply) GetGroups() int64 {
	if x != nil {
		return x.Groups
	}
	return 0
}

func (x *SpaceSettingReply) GetComic() int64 {
	if x != nil {
		return x.Comic
	}
	return 0
}

func (x *SpaceSettingReply) GetBBq() int64 {
	if x != nil {
		return x.BBq
	}
	return 0
}

func (x *SpaceSettingReply) GetDressUp() int64 {
	if x != nil {
		return x.DressUp
	}
	return 0
}

func (x *SpaceSettingReply) GetDisableFollowing() int64 {
	if x != nil {
		return x.DisableFollowing
	}
	return 0
}

func (x *SpaceSettingReply) GetLivePlayback() int64 {
	if x != nil {
		return x.LivePlayback
	}
	return 0
}

func (x *SpaceSettingReply) GetCloseSpaceMedal() int64 {
	if x != nil {
		return x.CloseSpaceMedal
	}
	return 0
}

func (x *SpaceSettingReply) GetOnlyShowWearing() int64 {
	if x != nil {
		return x.OnlyShowWearing
	}
	return 0
}

func (x *SpaceSettingReply) GetDisableShowSchool() int64 {
	if x != nil {
		return x.DisableShowSchool
	}
	return 0
}

func (x *SpaceSettingReply) GetDisableShowNft() int64 {
	if x != nil {
		return x.DisableShowNft
	}
	return 0
}

type SpaceSettingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mid int64 `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
}

func (x *SpaceSettingReq) Reset() {
	*x = SpaceSettingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceSettingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceSettingReq) ProtoMessage() {}

func (x *SpaceSettingReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceSettingReq.ProtoReflect.Descriptor instead.
func (*SpaceSettingReq) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{10}
}

func (x *SpaceSettingReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

type TopPhoto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImgUrl      string `protobuf:"bytes,1,opt,name=img_url,json=imgUrl,proto3" json:"img_url,omitempty"`
	NightImgUrl string `protobuf:"bytes,2,opt,name=night_img_url,json=nightImgUrl,proto3" json:"night_img_url,omitempty"`
	Sid         int64  `protobuf:"varint,3,opt,name=sid,proto3" json:"sid,omitempty"`
}

func (x *TopPhoto) Reset() {
	*x = TopPhoto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopPhoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPhoto) ProtoMessage() {}

func (x *TopPhoto) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPhoto.ProtoReflect.Descriptor instead.
func (*TopPhoto) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{11}
}

func (x *TopPhoto) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

func (x *TopPhoto) GetNightImgUrl() string {
	if x != nil {
		return x.NightImgUrl
	}
	return ""
}

func (x *TopPhoto) GetSid() int64 {
	if x != nil {
		return x.Sid
	}
	return 0
}

type TopPhotoArc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Show bool   `protobuf:"varint,1,opt,name=show,proto3" json:"show,omitempty"`
	Aid  int64  `protobuf:"varint,2,opt,name=aid,proto3" json:"aid,omitempty"`
	Pic  string `protobuf:"bytes,3,opt,name=pic,proto3" json:"pic,omitempty"`
}

func (x *TopPhotoArc) Reset() {
	*x = TopPhotoArc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopPhotoArc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPhotoArc) ProtoMessage() {}

func (x *TopPhotoArc) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPhotoArc.ProtoReflect.Descriptor instead.
func (*TopPhotoArc) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{12}
}

func (x *TopPhotoArc) GetShow() bool {
	if x != nil {
		return x.Show
	}
	return false
}

func (x *TopPhotoArc) GetAid() int64 {
	if x != nil {
		return x.Aid
	}
	return 0
}

func (x *TopPhotoArc) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

type TopPhotoArcCancelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mid int64 `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
}

func (x *TopPhotoArcCancelReq) Reset() {
	*x = TopPhotoArcCancelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopPhotoArcCancelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPhotoArcCancelReq) ProtoMessage() {}

func (x *TopPhotoArcCancelReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPhotoArcCancelReq.ProtoReflect.Descriptor instead.
func (*TopPhotoArcCancelReq) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{13}
}

func (x *TopPhotoArcCancelReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

type TopPhotoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopPhoto    *TopPhoto    `protobuf:"bytes,1,opt,name=top_photo,json=topPhoto,proto3" json:"top_photo,omitempty"`
	TopPhotoArc *TopPhotoArc `protobuf:"bytes,2,opt,name=top_photo_arc,json=topPhotoArc,proto3" json:"top_photo_arc,omitempty"`
}

func (x *TopPhotoReply) Reset() {
	*x = TopPhotoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopPhotoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPhotoReply) ProtoMessage() {}

func (x *TopPhotoReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPhotoReply.ProtoReflect.Descriptor instead.
func (*TopPhotoReply) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{14}
}

func (x *TopPhotoReply) GetTopPhoto() *TopPhoto {
	if x != nil {
		return x.TopPhoto
	}
	return nil
}

func (x *TopPhotoReply) GetTopPhotoArc() *TopPhotoArc {
	if x != nil {
		return x.TopPhotoArc
	}
	return nil
}

type TopPhotoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobiapp  string `protobuf:"bytes,1,opt,name=mobiapp,proto3" json:"mobiapp,omitempty"`
	Mid      int64  `protobuf:"varint,2,opt,name=mid,proto3" json:"mid,omitempty"`
	Build    int32  `protobuf:"varint,3,opt,name=build,proto3" json:"build,omitempty"`
	Device   string `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	LoginMid int64  `protobuf:"varint,5,opt,name=login_mid,json=loginMid,proto3" json:"login_mid,omitempty"`
}

func (x *TopPhotoReq) Reset() {
	*x = TopPhotoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopPhotoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPhotoReq) ProtoMessage() {}

func (x *TopPhotoReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPhotoReq.ProtoReflect.Descriptor instead.
func (*TopPhotoReq) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{15}
}

func (x *TopPhotoReq) GetMobiapp() string {
	if x != nil {
		return x.Mobiapp
	}
	return ""
}

func (x *TopPhotoReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *TopPhotoReq) GetBuild() int32 {
	if x != nil {
		return x.Build
	}
	return 0
}

func (x *TopPhotoReq) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *TopPhotoReq) GetLoginMid() int64 {
	if x != nil {
		return x.LoginMid
	}
	return 0
}

type UpActivityTabReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mid     int64  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	State   int32  `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	TabCont int64  `protobuf:"varint,3,opt,name=tab_cont,json=tabCont,proto3" json:"tab_cont,omitempty"`
	TabName string `protobuf:"bytes,4,opt,name=tab_name,json=tabName,proto3" json:"tab_name,omitempty"`
}

func (x *UpActivityTabReq) Reset() {
	*x = UpActivityTabReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpActivityTabReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpActivityTabReq) ProtoMessage() {}

func (x *UpActivityTabReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpActivityTabReq.ProtoReflect.Descriptor instead.
func (*UpActivityTabReq) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{16}
}

func (x *UpActivityTabReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *UpActivityTabReq) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *UpActivityTabReq) GetTabCont() int64 {
	if x != nil {
		return x.TabCont
	}
	return 0
}

func (x *UpActivityTabReq) GetTabName() string {
	if x != nil {
		return x.TabName
	}
	return ""
}

type UpActivityTabResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UpActivityTabResp) Reset() {
	*x = UpActivityTabResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpActivityTabResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpActivityTabResp) ProtoMessage() {}

func (x *UpActivityTabResp) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpActivityTabResp.ProtoReflect.Descriptor instead.
func (*UpActivityTabResp) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{17}
}

func (x *UpActivityTabResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpRcmdBlackListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpRcmdBlackListReply) Reset() {
	*x = UpRcmdBlackListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpRcmdBlackListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpRcmdBlackListReply) ProtoMessage() {}

func (x *UpRcmdBlackListReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpRcmdBlackListReply.ProtoReflect.Descriptor instead.
func (*UpRcmdBlackListReply) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{18}
}

type UserTabReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TabType   int32  `protobuf:"varint,1,opt,name=tab_type,json=tabType,proto3" json:"tab_type,omitempty"`
	Mid       int64  `protobuf:"varint,2,opt,name=mid,proto3" json:"mid,omitempty"`
	TabName   string `protobuf:"bytes,3,opt,name=tab_name,json=tabName,proto3" json:"tab_name,omitempty"`
	TabOrder  int32  `protobuf:"varint,4,opt,name=tab_order,json=tabOrder,proto3" json:"tab_order,omitempty"`
	TabCont   int64  `protobuf:"varint,5,opt,name=tab_cont,json=tabCont,proto3" json:"tab_cont,omitempty"`
	IsDefault int32  `protobuf:"varint,6,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	H5Link    string `protobuf:"bytes,7,opt,name=h5_link,json=h5Link,proto3" json:"h5_link,omitempty"`
}

func (x *UserTabReply) Reset() {
	*x = UserTabReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserTabReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTabReply) ProtoMessage() {}

func (x *UserTabReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTabReply.ProtoReflect.Descriptor instead.
func (*UserTabReply) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{19}
}

func (x *UserTabReply) GetTabType() int32 {
	if x != nil {
		return x.TabType
	}
	return 0
}

func (x *UserTabReply) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *UserTabReply) GetTabName() string {
	if x != nil {
		return x.TabName
	}
	return ""
}

func (x *UserTabReply) GetTabOrder() int32 {
	if x != nil {
		return x.TabOrder
	}
	return 0
}

func (x *UserTabReply) GetTabCont() int64 {
	if x != nil {
		return x.TabCont
	}
	return 0
}

func (x *UserTabReply) GetIsDefault() int32 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

func (x *UserTabReply) GetH5Link() string {
	if x != nil {
		return x.H5Link
	}
	return ""
}

type UserTabReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mid   int64 `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Plat  int32 `protobuf:"varint,2,opt,name=plat,proto3" json:"plat,omitempty"`
	Build int32 `protobuf:"varint,3,opt,name=build,proto3" json:"build,omitempty"`
}

func (x *UserTabReq) Reset() {
	*x = UserTabReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserTabReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTabReq) ProtoMessage() {}

func (x *UserTabReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTabReq.ProtoReflect.Descriptor instead.
func (*UserTabReq) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{20}
}

func (x *UserTabReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *UserTabReq) GetPlat() int32 {
	if x != nil {
		return x.Plat
	}
	return 0
}

func (x *UserTabReq) GetBuild() int32 {
	if x != nil {
		return x.Build
	}
	return 0
}

type WhitelistAddReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddOk bool `protobuf:"varint,1,opt,name=add_ok,json=addOk,proto3" json:"add_ok,omitempty"`
}

func (x *WhitelistAddReply) Reset() {
	*x = WhitelistAddReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhitelistAddReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistAddReply) ProtoMessage() {}

func (x *WhitelistAddReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistAddReply.ProtoReflect.Descriptor instead.
func (*WhitelistAddReply) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{21}
}

func (x *WhitelistAddReply) GetAddOk() bool {
	if x != nil {
		return x.AddOk
	}
	return false
}

type WhitelistAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mid   int64 `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Stime int64 `protobuf:"varint,2,opt,name=stime,proto3" json:"stime,omitempty"`
	Etime int64 `protobuf:"varint,3,opt,name=etime,proto3" json:"etime,omitempty"`
}

func (x *WhitelistAddReq) Reset() {
	*x = WhitelistAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhitelistAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistAddReq) ProtoMessage() {}

func (x *WhitelistAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistAddReq.ProtoReflect.Descriptor instead.
func (*WhitelistAddReq) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{22}
}

func (x *WhitelistAddReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *WhitelistAddReq) GetStime() int64 {
	if x != nil {
		return x.Stime
	}
	return 0
}

func (x *WhitelistAddReq) GetEtime() int64 {
	if x != nil {
		return x.Etime
	}
	return 0
}

type WhitelistReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsWhite bool `protobuf:"varint,1,opt,name=is_white,json=isWhite,proto3" json:"is_white,omitempty"`
}

func (x *WhitelistReply) Reset() {
	*x = WhitelistReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhitelistReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistReply) ProtoMessage() {}

func (x *WhitelistReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistReply.ProtoReflect.Descriptor instead.
func (*WhitelistReply) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{23}
}

func (x *WhitelistReply) GetIsWhite() bool {
	if x != nil {
		return x.IsWhite
	}
	return false
}

type WhitelistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mid int64 `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
}

func (x *WhitelistReq) Reset() {
	*x = WhitelistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhitelistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistReq) ProtoMessage() {}

func (x *WhitelistReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistReq.ProtoReflect.Descriptor instead.
func (*WhitelistReq) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{24}
}

func (x *WhitelistReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

type WhitelistUpReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpOk bool `protobuf:"varint,1,opt,name=up_ok,json=upOk,proto3" json:"up_ok,omitempty"`
}

func (x *WhitelistUpReply) Reset() {
	*x = WhitelistUpReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhitelistUpReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistUpReply) ProtoMessage() {}

func (x *WhitelistUpReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistUpReply.ProtoReflect.Descriptor instead.
func (*WhitelistUpReply) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{25}
}

func (x *WhitelistUpReply) GetUpOk() bool {
	if x != nil {
		return x.UpOk
	}
	return false
}

type WhitelistValidTimeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsWhite bool  `protobuf:"varint,1,opt,name=is_white,json=isWhite,proto3" json:"is_white,omitempty"`
	Stime   int64 `protobuf:"varint,2,opt,name=stime,proto3" json:"stime,omitempty"`
	Etime   int64 `protobuf:"varint,3,opt,name=etime,proto3" json:"etime,omitempty"`
}

func (x *WhitelistValidTimeReply) Reset() {
	*x = WhitelistValidTimeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_web_space_v1_space_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhitelistValidTimeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistValidTimeReply) ProtoMessage() {}

func (x *WhitelistValidTimeReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_web_space_v1_space_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistValidTimeReply.ProtoReflect.Descriptor instead.
func (*WhitelistValidTimeReply) Descriptor() ([]byte, []int) {
	return file_bilibili_web_space_v1_space_proto_rawDescGZIP(), []int{26}
}

func (x *WhitelistValidTimeReply) GetIsWhite() bool {
	if x != nil {
		return x.IsWhite
	}
	return false
}

func (x *WhitelistValidTimeReply) GetStime() int64 {
	if x != nil {
		return x.Stime
	}
	return 0
}

func (x *WhitelistValidTimeReply) GetEtime() int64 {
	if x != nil {
		return x.Etime
	}
	return 0
}

var File_bilibili_web_space_v1_space_proto protoreflect.FileDescriptor

var file_bilibili_web_space_v1_space_proto_rawDesc = []byte{
	0x0a, 0x21, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x77, 0x65, 0x62, 0x2f, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x15, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x77, 0x65,
	0x62, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x09, 0x0a, 0x07, 0x4e, 0x6f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x87, 0x02, 0x0a, 0x0d, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x69,
	0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x63, 0x6d,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x63, 0x6d, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x69, 0x6f, 0x73, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x69, 0x6f, 0x73, 0x55, 0x72, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69,
	0x64, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x6e, 0x64,
	0x72, 0x6f, 0x69, 0x64, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x74, 0x74, 0x6f,
	0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x22,
	0x23, 0x0a, 0x0f, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x6d, 0x69, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x09, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x4d, 0x61,
	0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6d, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x6d, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x69, 0x67, 0x68,
	0x74, 0x5f, 0x69, 0x6d, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x67,
	0x68, 0x74, 0x49, 0x6d, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x69, 0x73, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x22, 0x4a, 0x0a, 0x12, 0x50, 0x68, 0x6f, 0x74,
	0x6f, 0x4d, 0x61, 0x6c, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x34,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x62,
	0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x4d, 0x61, 0x6c, 0x6c, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x22, 0x56, 0x0a, 0x10, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x4d, 0x61, 0x6c,
	0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x6f, 0x62, 0x69,
	0x61, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x6f, 0x62, 0x69, 0x61,
	0x70, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x6d, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x22, 0x96, 0x01, 0x0a,
	0x0c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4a, 0x0a,
	0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30,
	0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x1a, 0x3a, 0x0a, 0x0c, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x63, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x22, 0x0a, 0x0e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x22, 0x61, 0x0a, 0x0e, 0x53, 0x65, 0x74,
	0x54, 0x6f, 0x70, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x6f, 0x62, 0x69, 0x61, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x6f,
	0x62, 0x69, 0x61, 0x70, 0x70, 0x12, 0x0f, 0x0a, 0x03, 0x69, 0x5f, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xa7, 0x04, 0x0a,
	0x11, 0x53, 0x70, 0x61, 0x63, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1b, 0x0a, 0x09,
	0x66, 0x61, 0x76, 0x5f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x66, 0x61, 0x76, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x69,
	0x6e, 0x73, 0x5f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x63, 0x6f, 0x69, 0x6e, 0x73, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x69,
	0x6b, 0x65, 0x73, 0x5f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x62,
	0x61, 0x6e, 0x67, 0x75, 0x6d, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x62, 0x61,
	0x6e, 0x67, 0x75, 0x6d, 0x69, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x5f,
	0x67, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x6d, 0x69, 0x63, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63,
	0x6f, 0x6d, 0x69, 0x63, 0x12, 0x11, 0x0a, 0x04, 0x62, 0x5f, 0x62, 0x71, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x62, 0x42, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x5f, 0x75, 0x70, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x55, 0x70, 0x12, 0x2b, 0x0a, 0x11, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x66, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x12,
	0x23, 0x0a, 0x0d, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6c, 0x69, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79,
	0x62, 0x61, 0x63, 0x6b, 0x12, 0x2a, 0x0a, 0x11, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x5f, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0f, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4d, 0x65, 0x64, 0x61, 0x6c,
	0x12, 0x2a, 0x0a, 0x11, 0x6f, 0x6e, 0x6c, 0x79, 0x5f, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x77, 0x65,
	0x61, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x6f, 0x6e, 0x6c,
	0x79, 0x53, 0x68, 0x6f, 0x77, 0x57, 0x65, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x2e, 0x0a, 0x13,
	0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x73, 0x63, 0x68,
	0x6f, 0x6f, 0x6c, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x64, 0x69, 0x73, 0x61, 0x62,
	0x6c, 0x65, 0x53, 0x68, 0x6f, 0x77, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x12, 0x28, 0x0a, 0x10,
	0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x6e, 0x66, 0x74,
	0x18, 0x10, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x68, 0x6f, 0x77, 0x4e, 0x66, 0x74, 0x22, 0x23, 0x0a, 0x0f, 0x53, 0x70, 0x61, 0x63, 0x65, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x22, 0x59, 0x0a, 0x08, 0x54,
	0x6f, 0x70, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x6d, 0x67, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x67, 0x55, 0x72, 0x6c,
	0x12, 0x22, 0x0a, 0x0d, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x69, 0x6d, 0x67, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x49, 0x6d,
	0x67, 0x55, 0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x73, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x0b, 0x54, 0x6f, 0x70, 0x50, 0x68, 0x6f,
	0x74, 0x6f, 0x41, 0x72, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x68, 0x6f, 0x77, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x73, 0x68, 0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x61, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x63, 0x22, 0x28, 0x0a,
	0x14, 0x54, 0x6f, 0x70, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x41, 0x72, 0x63, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x22, 0x95, 0x01, 0x0a, 0x0d, 0x54, 0x6f, 0x70, 0x50,
	0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3c, 0x0a, 0x09, 0x74, 0x6f, 0x70,
	0x5f, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x62,
	0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x08, 0x74,
	0x6f, 0x70, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x12, 0x46, 0x0a, 0x0d, 0x74, 0x6f, 0x70, 0x5f, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x5f, 0x61, 0x72, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x41,
	0x72, 0x63, 0x52, 0x0b, 0x74, 0x6f, 0x70, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x41, 0x72, 0x63, 0x22,
	0x84, 0x01, 0x0a, 0x0b, 0x54, 0x6f, 0x70, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x6f, 0x62, 0x69, 0x61, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x6f, 0x62, 0x69, 0x61, 0x70, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x5f, 0x6d, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x4d, 0x69, 0x64, 0x22, 0x70, 0x0a, 0x10, 0x55, 0x70, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x54, 0x61, 0x62, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x61, 0x62, 0x43, 0x6f, 0x6e, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x74, 0x61, 0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x74, 0x61, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x11, 0x55, 0x70, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x54, 0x61, 0x62, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x55, 0x70, 0x52, 0x63, 0x6d,
	0x64, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0xc6, 0x01, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x54, 0x61, 0x62, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x74, 0x61, 0x62, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x74, 0x61, 0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x74, 0x61, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x62, 0x5f,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x61, 0x62,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x5f, 0x63, 0x6f, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x61, 0x62, 0x43, 0x6f, 0x6e, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x69, 0x73, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x68, 0x35, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x68, 0x35, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x48, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72,
	0x54, 0x61, 0x62, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6c, 0x61, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6c, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x62, 0x75, 0x69, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x22, 0x2a, 0x0a, 0x11, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x64, 0x64, 0x5f, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x64, 0x64, 0x4f, 0x6b, 0x22, 0x4f,
	0x0a, 0x0f, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x6d, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x22,
	0x2b, 0x0a, 0x0e, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x77, 0x68, 0x69, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x57, 0x68, 0x69, 0x74, 0x65, 0x22, 0x20, 0x0a, 0x0c,
	0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x22, 0x27,
	0x0a, 0x10, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x55, 0x70, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x13, 0x0a, 0x05, 0x75, 0x70, 0x5f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x75, 0x70, 0x4f, 0x6b, 0x22, 0x60, 0x0a, 0x17, 0x57, 0x68, 0x69, 0x74, 0x65,
	0x6c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x77, 0x68, 0x69, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x57, 0x68, 0x69, 0x74, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x2a, 0x31, 0x0a, 0x0c, 0x54, 0x6f, 0x70,
	0x50, 0x68, 0x6f, 0x74, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x49, 0x43, 0x10, 0x01, 0x12,
	0x0b, 0x0a, 0x07, 0x41, 0x52, 0x43, 0x48, 0x49, 0x56, 0x45, 0x10, 0x02, 0x42, 0x42, 0x5a, 0x40,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x58, 0x69, 0x61, 0x6f, 0x4d,
	0x69, 0x6b, 0x75, 0x30, 0x31, 0x2f, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2d, 0x67,
	0x72, 0x70, 0x63, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x6f, 0x2f, 0x62, 0x69, 0x6c, 0x69, 0x62,
	0x69, 0x6c, 0x69, 0x2f, 0x77, 0x65, 0x62, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2f, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bilibili_web_space_v1_space_proto_rawDescOnce sync.Once
	file_bilibili_web_space_v1_space_proto_rawDescData = file_bilibili_web_space_v1_space_proto_rawDesc
)

func file_bilibili_web_space_v1_space_proto_rawDescGZIP() []byte {
	file_bilibili_web_space_v1_space_proto_rawDescOnce.Do(func() {
		file_bilibili_web_space_v1_space_proto_rawDescData = protoimpl.X.CompressGZIP(file_bilibili_web_space_v1_space_proto_rawDescData)
	})
	return file_bilibili_web_space_v1_space_proto_rawDescData
}

var file_bilibili_web_space_v1_space_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bilibili_web_space_v1_space_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_bilibili_web_space_v1_space_proto_goTypes = []interface{}{
	(TopPhotoType)(0),               // 0: bilibili.web.space.v1.TopPhotoType
	(*NoReply)(nil),                 // 1: bilibili.web.space.v1.NoReply
	(*OfficialReply)(nil),           // 2: bilibili.web.space.v1.OfficialReply
	(*OfficialRequest)(nil),         // 3: bilibili.web.space.v1.OfficialRequest
	(*PhotoMall)(nil),               // 4: bilibili.web.space.v1.PhotoMall
	(*PhotoMallListReply)(nil),      // 5: bilibili.web.space.v1.PhotoMallListReply
	(*PhotoMallListReq)(nil),        // 6: bilibili.web.space.v1.PhotoMallListReq
	(*PrivacyReply)(nil),            // 7: bilibili.web.space.v1.PrivacyReply
	(*PrivacyRequest)(nil),          // 8: bilibili.web.space.v1.PrivacyRequest
	(*SetTopPhotoReq)(nil),          // 9: bilibili.web.space.v1.SetTopPhotoReq
	(*SpaceSettingReply)(nil),       // 10: bilibili.web.space.v1.SpaceSettingReply
	(*SpaceSettingReq)(nil),         // 11: bilibili.web.space.v1.SpaceSettingReq
	(*TopPhoto)(nil),                // 12: bilibili.web.space.v1.TopPhoto
	(*TopPhotoArc)(nil),             // 13: bilibili.web.space.v1.TopPhotoArc
	(*TopPhotoArcCancelReq)(nil),    // 14: bilibili.web.space.v1.TopPhotoArcCancelReq
	(*TopPhotoReply)(nil),           // 15: bilibili.web.space.v1.TopPhotoReply
	(*TopPhotoReq)(nil),             // 16: bilibili.web.space.v1.TopPhotoReq
	(*UpActivityTabReq)(nil),        // 17: bilibili.web.space.v1.UpActivityTabReq
	(*UpActivityTabResp)(nil),       // 18: bilibili.web.space.v1.UpActivityTabResp
	(*UpRcmdBlackListReply)(nil),    // 19: bilibili.web.space.v1.UpRcmdBlackListReply
	(*UserTabReply)(nil),            // 20: bilibili.web.space.v1.UserTabReply
	(*UserTabReq)(nil),              // 21: bilibili.web.space.v1.UserTabReq
	(*WhitelistAddReply)(nil),       // 22: bilibili.web.space.v1.WhitelistAddReply
	(*WhitelistAddReq)(nil),         // 23: bilibili.web.space.v1.WhitelistAddReq
	(*WhitelistReply)(nil),          // 24: bilibili.web.space.v1.WhitelistReply
	(*WhitelistReq)(nil),            // 25: bilibili.web.space.v1.WhitelistReq
	(*WhitelistUpReply)(nil),        // 26: bilibili.web.space.v1.WhitelistUpReply
	(*WhitelistValidTimeReply)(nil), // 27: bilibili.web.space.v1.WhitelistValidTimeReply
	nil,                             // 28: bilibili.web.space.v1.PrivacyReply.PrivacyEntry
}
var file_bilibili_web_space_v1_space_proto_depIdxs = []int32{
	4,  // 0: bilibili.web.space.v1.PhotoMallListReply.list:type_name -> bilibili.web.space.v1.PhotoMall
	28, // 1: bilibili.web.space.v1.PrivacyReply.privacy:type_name -> bilibili.web.space.v1.PrivacyReply.PrivacyEntry
	12, // 2: bilibili.web.space.v1.TopPhotoReply.top_photo:type_name -> bilibili.web.space.v1.TopPhoto
	13, // 3: bilibili.web.space.v1.TopPhotoReply.top_photo_arc:type_name -> bilibili.web.space.v1.TopPhotoArc
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_bilibili_web_space_v1_space_proto_init() }
func file_bilibili_web_space_v1_space_proto_init() {
	if File_bilibili_web_space_v1_space_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bilibili_web_space_v1_space_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfficialReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfficialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhotoMall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhotoMallListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhotoMallListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrivacyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrivacyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetTopPhotoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceSettingReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceSettingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopPhoto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopPhotoArc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopPhotoArcCancelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopPhotoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopPhotoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpActivityTabReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpActivityTabResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpRcmdBlackListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserTabReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserTabReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhitelistAddReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhitelistAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhitelistReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhitelistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhitelistUpReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_web_space_v1_space_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhitelistValidTimeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bilibili_web_space_v1_space_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bilibili_web_space_v1_space_proto_goTypes,
		DependencyIndexes: file_bilibili_web_space_v1_space_proto_depIdxs,
		EnumInfos:         file_bilibili_web_space_v1_space_proto_enumTypes,
		MessageInfos:      file_bilibili_web_space_v1_space_proto_msgTypes,
	}.Build()
	File_bilibili_web_space_v1_space_proto = out.File
	file_bilibili_web_space_v1_space_proto_rawDesc = nil
	file_bilibili_web_space_v1_space_proto_goTypes = nil
	file_bilibili_web_space_v1_space_proto_depIdxs = nil
}
