// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: bilibili/app/click/v1/heartbeat.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayState int32

const (
	PlayState_STATE_UNKNOWN PlayState = 0
	PlayState_PREPARING PlayState = 1
	PlayState_PREPARED PlayState = 2
	PlayState_PLAYING PlayState = 3
	PlayState_PAUSED PlayState = 4
	PlayState_STOPPED PlayState = 5
	PlayState_FAILED PlayState = 6
)

// Enum value maps for PlayState.
var (
	PlayState_name = map[int32]string{
		0: "STATE_UNKNOWN",
		1: "PREPARING",
		2: "PREPARED",
		3: "PLAYING",
		4: "PAUSED",
		5: "STOPPED",
		6: "FAILED",
	}
	PlayState_value = map[string]int32{
		"STATE_UNKNOWN": 0,
		"PREPARING":     1,
		"PREPARED":      2,
		"PLAYING":       3,
		"PAUSED":        4,
		"STOPPED":       5,
		"FAILED":        6,
	}
)

func (x PlayState) Enum() *PlayState {
	p := new(PlayState)
	*p = x
	return p
}

func (x PlayState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayState) Descriptor() protoreflect.EnumDescriptor {
	return file_bilibili_app_click_v1_heartbeat_proto_enumTypes[0].Descriptor()
}

func (PlayState) Type() protoreflect.EnumType {
	return &file_bilibili_app_click_v1_heartbeat_proto_enumTypes[0]
}

func (x PlayState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayState.Descriptor instead.
func (PlayState) EnumDescriptor() ([]byte, []int) {
	return file_bilibili_app_click_v1_heartbeat_proto_rawDescGZIP(), []int{0}
}

type Stage int32

const (
	Stage_STAGE_UNKNOWN Stage = 0
	Stage_START Stage = 1
	Stage_END Stage = 2
	Stage_SAMPLE Stage = 3
)

// Enum value maps for Stage.
var (
	Stage_name = map[int32]string{
		0: "STAGE_UNKNOWN",
		1: "START",
		2: "END",
		3: "SAMPLE",
	}
	Stage_value = map[string]int32{
		"STAGE_UNKNOWN": 0,
		"START":         1,
		"END":           2,
		"SAMPLE":        3,
	}
)

func (x Stage) Enum() *Stage {
	p := new(Stage)
	*p = x
	return p
}

func (x Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_bilibili_app_click_v1_heartbeat_proto_enumTypes[1].Descriptor()
}

func (Stage) Type() protoreflect.EnumType {
	return &file_bilibili_app_click_v1_heartbeat_proto_enumTypes[1]
}

func (x Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stage.Descriptor instead.
func (Stage) EnumDescriptor() ([]byte, []int) {
	return file_bilibili_app_click_v1_heartbeat_proto_rawDescGZIP(), []int{1}
}

// 账户信息
type AccountInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mid uint64 `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_click_v1_heartbeat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_click_v1_heartbeat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_bilibili_app_click_v1_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *AccountInfo) GetMid() uint64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

type AppInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopPageClass string `protobuf:"bytes,1,opt,name=top_page_class,json=topPageClass,proto3" json:"top_page_class,omitempty"`
	// 客户端首次启动时的毫秒时间戳
	Ftime int64 `protobuf:"varint,2,opt,name=ftime,proto3" json:"ftime,omitempty"`
	Did string `protobuf:"bytes,3,opt,name=did,proto3" json:"did,omitempty"`
}

func (x *AppInfo) Reset() {
	*x = AppInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_click_v1_heartbeat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInfo) ProtoMessage() {}

func (x *AppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_click_v1_heartbeat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInfo.ProtoReflect.Descriptor instead.
func (*AppInfo) Descriptor() ([]byte, []int) {
	return file_bilibili_app_click_v1_heartbeat_proto_rawDescGZIP(), []int{1}
}

func (x *AppInfo) GetTopPageClass() string {
	if x != nil {
		return x.TopPageClass
	}
	return ""
}

func (x *AppInfo) GetFtime() int64 {
	if x != nil {
		return x.Ftime
	}
	return 0
}

func (x *AppInfo) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

// 心跳补充信息
type Extra struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Refer string `protobuf:"bytes,2,opt,name=refer,proto3" json:"refer,omitempty"`
}

func (x *Extra) Reset() {
	*x = Extra{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_click_v1_heartbeat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Extra) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extra) ProtoMessage() {}

func (x *Extra) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_click_v1_heartbeat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extra.ProtoReflect.Descriptor instead.
func (*Extra) Descriptor() ([]byte, []int) {
	return file_bilibili_app_click_v1_heartbeat_proto_rawDescGZIP(), []int{2}
}

func (x *Extra) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *Extra) GetRefer() string {
	if x != nil {
		return x.Refer
	}
	return ""
}

type HeartBeatReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HeartBeatReply) Reset() {
	*x = HeartBeatReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_click_v1_heartbeat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatReply) ProtoMessage() {}

func (x *HeartBeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_click_v1_heartbeat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatReply.ProtoReflect.Descriptor instead.
func (*HeartBeatReply) Descriptor() ([]byte, []int) {
	return file_bilibili_app_click_v1_heartbeat_proto_rawDescGZIP(), []int{3}
}

type HeartBeatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionV2 string `protobuf:"bytes,1,opt,name=session_v2,json=sessionV2,proto3" json:"session_v2,omitempty"`
	Stage Stage `protobuf:"varint,2,opt,name=stage,proto3,enum=bilibili.app.click.v1.Stage" json:"stage,omitempty"`
	// 流加载失败timeout
	StreamTimeout uint64 `protobuf:"varint,3,opt,name=stream_timeout,json=streamTimeout,proto3" json:"stream_timeout,omitempty"`
	BatchFrequency uint64 `protobuf:"varint,4,opt,name=batch_frequency,json=batchFrequency,proto3" json:"batch_frequency,omitempty"`
	Frequency float32 `protobuf:"fixed32,5,opt,name=frequency,proto3" json:"frequency,omitempty"`
	VideoMeta *VideoMeta `protobuf:"bytes,6,opt,name=video_meta,json=videoMeta,proto3" json:"video_meta,omitempty"`
	AppInfo *AppInfo `protobuf:"bytes,7,opt,name=app_info,json=appInfo,proto3" json:"app_info,omitempty"`
	AccountInfo *AccountInfo `protobuf:"bytes,8,opt,name=account_info,json=accountInfo,proto3" json:"account_info,omitempty"`
	PreProcessResult *PreProcessResult `protobuf:"bytes,9,opt,name=pre_process_result,json=preProcessResult,proto3" json:"pre_process_result,omitempty"`
	PlayerStatus []*PlayerStatus `protobuf:"bytes,10,rep,name=player_status,json=playerStatus,proto3" json:"player_status,omitempty"`
	VideoInfo *VideoInfo `protobuf:"bytes,11,opt,name=video_info,json=videoInfo,proto3" json:"video_info,omitempty"`
}

func (x *HeartBeatReq) Reset() {
	*x = HeartBeatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_click_v1_heartbeat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatReq) ProtoMessage() {}

func (x *HeartBeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_click_v1_heartbeat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatReq.ProtoReflect.Descriptor instead.
func (*HeartBeatReq) Descriptor() ([]byte, []int) {
	return file_bilibili_app_click_v1_heartbeat_proto_rawDescGZIP(), []int{4}
}

func (x *HeartBeatReq) GetSessionV2() string {
	if x != nil {
		return x.SessionV2
	}
	return ""
}

func (x *HeartBeatReq) GetStage() Stage {
	if x != nil {
		return x.Stage
	}
	return Stage_STAGE_UNKNOWN
}

func (x *HeartBeatReq) GetStreamTimeout() uint64 {
	if x != nil {
		return x.StreamTimeout
	}
	return 0
}

func (x *HeartBeatReq) GetBatchFrequency() uint64 {
	if x != nil {
		return x.BatchFrequency
	}
	return 0
}

func (x *HeartBeatReq) GetFrequency() float32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *HeartBeatReq) GetVideoMeta() *VideoMeta {
	if x != nil {
		return x.VideoMeta
	}
	return nil
}

func (x *HeartBeatReq) GetAppInfo() *AppInfo {
	if x != nil {
		return x.AppInfo
	}
	return nil
}

func (x *HeartBeatReq) GetAccountInfo() *AccountInfo {
	if x != nil {
		return x.AccountInfo
	}
	return nil
}

func (x *HeartBeatReq) GetPreProcessResult() *PreProcessResult {
	if x != nil {
		return x.PreProcessResult
	}
	return nil
}

func (x *HeartBeatReq) GetPlayerStatus() []*PlayerStatus {
	if x != nil {
		return x.PlayerStatus
	}
	return nil
}

func (x *HeartBeatReq) GetVideoInfo() *VideoInfo {
	if x != nil {
		return x.VideoInfo
	}
	return nil
}

type PlayerStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaybackRate float32 `protobuf:"fixed32,1,opt,name=playback_rate,json=playbackRate,proto3" json:"playback_rate,omitempty"`
	Progress uint64 `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	PlayState PlayState `protobuf:"varint,3,opt,name=play_state,json=playState,proto3,enum=bilibili.app.click.v1.PlayState" json:"play_state,omitempty"`
	IsBuffering bool `protobuf:"varint,4,opt,name=is_buffering,json=isBuffering,proto3" json:"is_buffering,omitempty"`
}

func (x *PlayerStatus) Reset() {
	*x = PlayerStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_click_v1_heartbeat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStatus) ProtoMessage() {}

func (x *PlayerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_click_v1_heartbeat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStatus.ProtoReflect.Descriptor instead.
func (*PlayerStatus) Descriptor() ([]byte, []int) {
	return file_bilibili_app_click_v1_heartbeat_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerStatus) GetPlaybackRate() float32 {
	if x != nil {
		return x.PlaybackRate
	}
	return 0
}

func (x *PlayerStatus) GetProgress() uint64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *PlayerStatus) GetPlayState() PlayState {
	if x != nil {
		return x.PlayState
	}
	return PlayState_STATE_UNKNOWN
}

func (x *PlayerStatus) GetIsBuffering() bool {
	if x != nil {
		return x.IsBuffering
	}
	return false
}

type PreProcessResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vt int64 `protobuf:"varint,1,opt,name=vt,proto3" json:"vt,omitempty"`
}

func (x *PreProcessResult) Reset() {
	*x = PreProcessResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_click_v1_heartbeat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreProcessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreProcessResult) ProtoMessage() {}

func (x *PreProcessResult) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_click_v1_heartbeat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreProcessResult.ProtoReflect.Descriptor instead.
func (*PreProcessResult) Descriptor() ([]byte, []int) {
	return file_bilibili_app_click_v1_heartbeat_proto_rawDescGZIP(), []int{6}
}

func (x *PreProcessResult) GetVt() int64 {
	if x != nil {
		return x.Vt
	}
	return 0
}

type VideoInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CidDuration uint64 `protobuf:"varint,1,opt,name=cid_duration,json=cidDuration,proto3" json:"cid_duration,omitempty"`
}

func (x *VideoInfo) Reset() {
	*x = VideoInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_click_v1_heartbeat_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInfo) ProtoMessage() {}

func (x *VideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_click_v1_heartbeat_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInfo.ProtoReflect.Descriptor instead.
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return file_bilibili_app_click_v1_heartbeat_proto_rawDescGZIP(), []int{7}
}

func (x *VideoInfo) GetCidDuration() uint64 {
	if x != nil {
		return x.CidDuration
	}
	return 0
}

type VideoMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Aid uint64 `protobuf:"varint,1,opt,name=aid,proto3" json:"aid,omitempty"`
	Cid uint64 `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (x *VideoMeta) Reset() {
	*x = VideoMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_app_click_v1_heartbeat_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMeta) ProtoMessage() {}

func (x *VideoMeta) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_app_click_v1_heartbeat_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMeta.ProtoReflect.Descriptor instead.
func (*VideoMeta) Descriptor() ([]byte, []int) {
	return file_bilibili_app_click_v1_heartbeat_proto_rawDescGZIP(), []int{8}
}

func (x *VideoMeta) GetAid() uint64 {
	if x != nil {
		return x.Aid
	}
	return 0
}

func (x *VideoMeta) GetCid() uint64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

var File_bilibili_app_click_v1_heartbeat_proto protoreflect.FileDescriptor

var file_bilibili_app_click_v1_heartbeat_proto_rawDesc = []byte{
	0x0a, 0x25, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x63,
	0x6c, 0x69, 0x63, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c,
	0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x76, 0x31, 0x22, 0x1f,
	0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x22,
	0x57, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x6f,
	0x70, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x74, 0x6f, 0x70, 0x50, 0x61, 0x67, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x66, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x66, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x22, 0x37, 0x0a, 0x05, 0x45, 0x78, 0x74, 0x72,
	0x61, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x66, 0x65,
	0x72, 0x22, 0x10, 0x0a, 0x0e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0xf4, 0x04, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x76, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x56, 0x32, 0x12, 0x32, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70,
	0x70, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x27,
	0x0a, 0x0f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x62, 0x61, 0x74, 0x63, 0x68, 0x46, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x66, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x3f, 0x0a, 0x0a, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x6d,
	0x65, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x62, 0x69, 0x6c, 0x69,
	0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x76,
	0x31, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x09, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x39, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62,
	0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x61, 0x70, 0x70, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x45, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69,
	0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x55, 0x0a, 0x12, 0x70, 0x72, 0x65, 0x5f,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e,
	0x61, 0x70, 0x70, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x65,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x10, 0x70,
	0x72, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x48, 0x0a, 0x0d, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c,
	0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0c, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3f, 0x0a, 0x0a, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x63, 0x6c, 0x69,
	0x63, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x09, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xb3, 0x01, 0x0a, 0x0c, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x70,
	0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x61, 0x74, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x3f, 0x0a, 0x0a,
	0x70, 0x6c, 0x61, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x20, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x2e,
	0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x69, 0x73, 0x5f, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x69, 0x6e, 0x67,
	0x22, 0x22, 0x0a, 0x10, 0x50, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x76, 0x74, 0x22, 0x2e, 0x0a, 0x09, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x69, 0x64, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x63, 0x69, 0x64, 0x44, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2f, 0x0a, 0x09, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x65, 0x74,
	0x61, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x61, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x63, 0x69, 0x64, 0x2a, 0x6d, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x52, 0x45, 0x50, 0x41, 0x52, 0x49,
	0x4e, 0x47, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x52, 0x45, 0x50, 0x41, 0x52, 0x45, 0x44,
	0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x4c, 0x41, 0x59, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12,
	0x0a, 0x0a, 0x06, 0x50, 0x41, 0x55, 0x53, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c,
	0x45, 0x44, 0x10, 0x06, 0x2a, 0x3a, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x11, 0x0a,
	0x0d, 0x53, 0x54, 0x41, 0x47, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x45,
	0x4e, 0x44, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x41, 0x4d, 0x50, 0x4c, 0x45, 0x10, 0x03,
	0x32, 0x07, 0x0a, 0x05, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x58, 0x69, 0x61, 0x6f, 0x4d, 0x69, 0x6b, 0x75,
	0x30, 0x31, 0x2f, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2d, 0x67, 0x72, 0x70, 0x63,
	0x2d, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x6f, 0x2f, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69,
	0x2f, 0x61, 0x70, 0x70, 0x2f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bilibili_app_click_v1_heartbeat_proto_rawDescOnce sync.Once
	file_bilibili_app_click_v1_heartbeat_proto_rawDescData = file_bilibili_app_click_v1_heartbeat_proto_rawDesc
)

func file_bilibili_app_click_v1_heartbeat_proto_rawDescGZIP() []byte {
	file_bilibili_app_click_v1_heartbeat_proto_rawDescOnce.Do(func() {
		file_bilibili_app_click_v1_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(file_bilibili_app_click_v1_heartbeat_proto_rawDescData)
	})
	return file_bilibili_app_click_v1_heartbeat_proto_rawDescData
}

var file_bilibili_app_click_v1_heartbeat_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bilibili_app_click_v1_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_bilibili_app_click_v1_heartbeat_proto_goTypes = []interface{}{
	(PlayState)(0),           // 0: bilibili.app.click.v1.PlayState
	(Stage)(0),               // 1: bilibili.app.click.v1.Stage
	(*AccountInfo)(nil),      // 2: bilibili.app.click.v1.AccountInfo
	(*AppInfo)(nil),          // 3: bilibili.app.click.v1.AppInfo
	(*Extra)(nil),            // 4: bilibili.app.click.v1.Extra
	(*HeartBeatReply)(nil),   // 5: bilibili.app.click.v1.HeartBeatReply
	(*HeartBeatReq)(nil),     // 6: bilibili.app.click.v1.HeartBeatReq
	(*PlayerStatus)(nil),     // 7: bilibili.app.click.v1.PlayerStatus
	(*PreProcessResult)(nil), // 8: bilibili.app.click.v1.PreProcessResult
	(*VideoInfo)(nil),        // 9: bilibili.app.click.v1.VideoInfo
	(*VideoMeta)(nil),        // 10: bilibili.app.click.v1.VideoMeta
}
var file_bilibili_app_click_v1_heartbeat_proto_depIdxs = []int32{
	1,  // 0: bilibili.app.click.v1.HeartBeatReq.stage:type_name -> bilibili.app.click.v1.Stage
	10, // 1: bilibili.app.click.v1.HeartBeatReq.video_meta:type_name -> bilibili.app.click.v1.VideoMeta
	3,  // 2: bilibili.app.click.v1.HeartBeatReq.app_info:type_name -> bilibili.app.click.v1.AppInfo
	2,  // 3: bilibili.app.click.v1.HeartBeatReq.account_info:type_name -> bilibili.app.click.v1.AccountInfo
	8,  // 4: bilibili.app.click.v1.HeartBeatReq.pre_process_result:type_name -> bilibili.app.click.v1.PreProcessResult
	7,  // 5: bilibili.app.click.v1.HeartBeatReq.player_status:type_name -> bilibili.app.click.v1.PlayerStatus
	9,  // 6: bilibili.app.click.v1.HeartBeatReq.video_info:type_name -> bilibili.app.click.v1.VideoInfo
	0,  // 7: bilibili.app.click.v1.PlayerStatus.play_state:type_name -> bilibili.app.click.v1.PlayState
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_bilibili_app_click_v1_heartbeat_proto_init() }
func file_bilibili_app_click_v1_heartbeat_proto_init() {
	if File_bilibili_app_click_v1_heartbeat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bilibili_app_click_v1_heartbeat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_click_v1_heartbeat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_click_v1_heartbeat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Extra); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_click_v1_heartbeat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_click_v1_heartbeat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_click_v1_heartbeat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_click_v1_heartbeat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreProcessResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_click_v1_heartbeat_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_app_click_v1_heartbeat_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bilibili_app_click_v1_heartbeat_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bilibili_app_click_v1_heartbeat_proto_goTypes,
		DependencyIndexes: file_bilibili_app_click_v1_heartbeat_proto_depIdxs,
		EnumInfos:         file_bilibili_app_click_v1_heartbeat_proto_enumTypes,
		MessageInfos:      file_bilibili_app_click_v1_heartbeat_proto_msgTypes,
	}.Build()
	File_bilibili_app_click_v1_heartbeat_proto = out.File
	file_bilibili_app_click_v1_heartbeat_proto_rawDesc = nil
	file_bilibili_app_click_v1_heartbeat_proto_goTypes = nil
	file_bilibili_app_click_v1_heartbeat_proto_depIdxs = nil
}
