// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: bilibili/im/interfaces/inner-interface/v1/api.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BanUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户mid
	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// 封禁业务
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// 封禁时间
	Time int32 `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	// 模式
	// 1:add 2:remove
	Mode int32 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *BanUser) Reset() {
	*x = BanUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_im_interfaces_inner_interface_v1_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BanUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanUser) ProtoMessage() {}

func (x *BanUser) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_im_interfaces_inner_interface_v1_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanUser.ProtoReflect.Descriptor instead.
func (*BanUser) Descriptor() ([]byte, []int) {
	return file_bilibili_im_interfaces_inner_interface_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *BanUser) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *BanUser) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *BanUser) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *BanUser) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type ReqOpBlacklist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 需要封禁/解封的用户信息
	BanUsers []*BanUser `protobuf:"bytes,1,rep,name=ban_users,json=banUsers,proto3" json:"ban_users,omitempty"`
}

func (x *ReqOpBlacklist) Reset() {
	*x = ReqOpBlacklist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_im_interfaces_inner_interface_v1_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqOpBlacklist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqOpBlacklist) ProtoMessage() {}

func (x *ReqOpBlacklist) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_im_interfaces_inner_interface_v1_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqOpBlacklist.ProtoReflect.Descriptor instead.
func (*ReqOpBlacklist) Descriptor() ([]byte, []int) {
	return file_bilibili_im_interfaces_inner_interface_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *ReqOpBlacklist) GetBanUsers() []*BanUser {
	if x != nil {
		return x.BanUsers
	}
	return nil
}

type RspOpBlacklist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FailedUsers []uint64 `protobuf:"varint,1,rep,packed,name=failed_users,json=failedUsers,proto3" json:"failed_users,omitempty"`
}

func (x *RspOpBlacklist) Reset() {
	*x = RspOpBlacklist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bilibili_im_interfaces_inner_interface_v1_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspOpBlacklist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspOpBlacklist) ProtoMessage() {}

func (x *RspOpBlacklist) ProtoReflect() protoreflect.Message {
	mi := &file_bilibili_im_interfaces_inner_interface_v1_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspOpBlacklist.ProtoReflect.Descriptor instead.
func (*RspOpBlacklist) Descriptor() ([]byte, []int) {
	return file_bilibili_im_interfaces_inner_interface_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *RspOpBlacklist) GetFailedUsers() []uint64 {
	if x != nil {
		return x.FailedUsers
	}
	return nil
}

var File_bilibili_im_interfaces_inner_interface_v1_api_proto protoreflect.FileDescriptor

var file_bilibili_im_interfaces_inner_interface_v1_api_proto_rawDesc = []byte{
	0x0a, 0x33, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2f, 0x69, 0x6d, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2f, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2d, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x28, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e,
	0x69, 0x6d, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x6e,
	0x65, 0x72, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x22,
	0x59, 0x0a, 0x07, 0x42, 0x61, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x60, 0x0a, 0x0e, 0x52, 0x65,
	0x71, 0x4f, 0x70, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x4e, 0x0a, 0x09,
	0x62, 0x61, 0x6e, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x31, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x6e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x22, 0x33, 0x0a, 0x0e,
	0x52, 0x73, 0x70, 0x4f, 0x70, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x04, 0x52, 0x0b, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x32, 0x96, 0x01, 0x0a, 0x0e, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x12, 0x83, 0x01, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x49, 0x6e, 0x6e, 0x12, 0x38, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c,
	0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x69,
	0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x71, 0x4f, 0x70, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74,
	0x1a, 0x38, 0x2e, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2e, 0x69, 0x6d, 0x2e, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x73, 0x70, 0x4f,
	0x70, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x56, 0x5a, 0x54, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x58, 0x69, 0x61, 0x6f, 0x4d, 0x69, 0x6b,
	0x75, 0x30, 0x31, 0x2f, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x2d, 0x67, 0x72, 0x70,
	0x63, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x6f, 0x2f, 0x62, 0x69, 0x6c, 0x69, 0x62, 0x69, 0x6c,
	0x69, 0x2f, 0x69, 0x6d, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2f,
	0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bilibili_im_interfaces_inner_interface_v1_api_proto_rawDescOnce sync.Once
	file_bilibili_im_interfaces_inner_interface_v1_api_proto_rawDescData = file_bilibili_im_interfaces_inner_interface_v1_api_proto_rawDesc
)

func file_bilibili_im_interfaces_inner_interface_v1_api_proto_rawDescGZIP() []byte {
	file_bilibili_im_interfaces_inner_interface_v1_api_proto_rawDescOnce.Do(func() {
		file_bilibili_im_interfaces_inner_interface_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_bilibili_im_interfaces_inner_interface_v1_api_proto_rawDescData)
	})
	return file_bilibili_im_interfaces_inner_interface_v1_api_proto_rawDescData
}

var file_bilibili_im_interfaces_inner_interface_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bilibili_im_interfaces_inner_interface_v1_api_proto_goTypes = []interface{}{
	(*BanUser)(nil),        // 0: bilibili.im.interface.inner.interface.v1.BanUser
	(*ReqOpBlacklist)(nil), // 1: bilibili.im.interface.inner.interface.v1.ReqOpBlacklist
	(*RspOpBlacklist)(nil), // 2: bilibili.im.interface.inner.interface.v1.RspOpBlacklist
}
var file_bilibili_im_interfaces_inner_interface_v1_api_proto_depIdxs = []int32{
	0, // 0: bilibili.im.interface.inner.interface.v1.ReqOpBlacklist.ban_users:type_name -> bilibili.im.interface.inner.interface.v1.BanUser
	1, // 1: bilibili.im.interface.inner.interface.v1.InnerInterface.UpdateListInn:input_type -> bilibili.im.interface.inner.interface.v1.ReqOpBlacklist
	2, // 2: bilibili.im.interface.inner.interface.v1.InnerInterface.UpdateListInn:output_type -> bilibili.im.interface.inner.interface.v1.RspOpBlacklist
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bilibili_im_interfaces_inner_interface_v1_api_proto_init() }
func file_bilibili_im_interfaces_inner_interface_v1_api_proto_init() {
	if File_bilibili_im_interfaces_inner_interface_v1_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bilibili_im_interfaces_inner_interface_v1_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BanUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_im_interfaces_inner_interface_v1_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqOpBlacklist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bilibili_im_interfaces_inner_interface_v1_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspOpBlacklist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bilibili_im_interfaces_inner_interface_v1_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bilibili_im_interfaces_inner_interface_v1_api_proto_goTypes,
		DependencyIndexes: file_bilibili_im_interfaces_inner_interface_v1_api_proto_depIdxs,
		MessageInfos:      file_bilibili_im_interfaces_inner_interface_v1_api_proto_msgTypes,
	}.Build()
	File_bilibili_im_interfaces_inner_interface_v1_api_proto = out.File
	file_bilibili_im_interfaces_inner_interface_v1_api_proto_rawDesc = nil
	file_bilibili_im_interfaces_inner_interface_v1_api_proto_goTypes = nil
	file_bilibili_im_interfaces_inner_interface_v1_api_proto_depIdxs = nil
}
